### ISSUE TITLE
Creation of a Belgium ruby devs manifesto

### ISSUE THREAD

**Issue by borisrorsvort** [brug-be/rubycamp-2016#1]
As @toch started to investigate common rates and wages, I'd like to include it in a more general reflexion around working conditions.
The goal would be to collectively create a draft document that would gather things that we would here in Belgium consider the ideal work conditions. 
Including wage rate range per seniority (also need to define seniority in context), working environment (office space, company culture, remote stuff, ...), perks, company structure & processes, tooling, community values, ...

It is not something that should be considered fixed as the job will evolve, but be regularly re-challenged.
In the creation of this document I see multiple objectives:
- prevent noobs to undervalue themselves and low rate jurisprudence for employer
- provide companies that can't pay much, ideas to remain attractive (perks, culture, tooling, ...)
- open the discussion about these subjects among us to raise solidarity and cohesion in the community

Any comments, re-scoping & frenchies are welcome obviously :)

ps: I expect it to be a little controversial but maybe we can still extract some great stuffs out of the discussion

**Comment by cimm** [comment]
Should we maybe start with a (anonymous) survey on the salaries / conditions / perks we have today? So we could make some statements as "the average Ruby dev in Belgium with 3 years experience earns €x / month with has a smartphone and laptop"?

**Comment by borisrorsvort** [comment]
yep good idea

**Comment by toch** [comment]
please discuss it on https://github.com/brug-be/rubybelgium-documents/issues/10 as it concerns the whole association

ofc feel free to progress on that topic during the rubycamp
